---
title: "R Workshop 2024 - Part 2"
author: "Hannah Damico"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(ggplot2)

```

# Understanding Your Data {.tabset}

## Reading & Viewing your Data



```{r}
# "/varidata/researchtemp/hpctmp/r_basics_2024/"
cyto_data <-
read_csv(file = "/varidata/researchtemp/hpctmp/r_basics_2024/cytomegalovirus.csv")
```


```{r}
# View(cyto_data)
```


### What kind of object do we have?

```{r}
class(cyto_data)
dim(cyto_data)
nrow(cyto_data)
ncol(cyto_data)

glimpse(cyto_data)
str(cyto_data)
```

### Categorical Variables

```{r}
# nominal variable
table(cyto_data$diagnosis)
# ordinal variable
table(cyto_data$prior.chemo)

cyto_data$prior.chemo <-
factor(cyto_data$prior.chemo, levels = 0:8)
```


### Continuous variable

```{r}
summary(cyto_data$age)
```


## Missing Data & Outlier Detection

```{r}
table(cyto_data$prior.radiation, useNA = "ifany")

library(DataExplorer)
# install.packages("DataExplorer")

plot_missing(cyto_data)
```


```{r}
summary(cyto_data$age)
```

## Plots 

%>% - pipe operator 


```{r}
cyto_data %>% 
  ggplot(aes(x = CD8.dose, y= CD34.dose, color = sex)) +
  geom_point()
```


```{r}
cyto_data %>% filter(prior.chemo %in% 0:8) %>% 
  ggplot(aes(x = prior.chemo)) +
  geom_bar()

```


```{r}
table(cyto_data$prior.radiation, useNA = "ifany")

cyto_data$sex <- factor(cyto_data$sex, levels = c("1", "0"))
cyto_data$sex2 <- ifelse(cyto_data$sex == "1", "Male", "Female")

cyto_data %>% 
  filter(prior.radiation %in% c(0,1)) %>% 
  ggplot(aes(x = TNC.dose, y = CD3.dose, color = sex)) +
  geom_point() + 
  facet_grid(.~prior.radiation) + 
  geom_smooth(method = "lm", se = F) +
  ggtitle("Dosage by Radiation Exposure") +
  ylab("CD3 Dose") + xlab("TNC Dose") + 
  theme_bw()
```


